ee = {
    "object": "whatsapp_business_account",
    "entry": [
        {
            "id": "100820822904886",
            "changes": [
                {
                    "value": {
                        "messaging_product": "whatsapp",
                        "metadata": {
                            "display_phone_number": "2349160000265",
                            "phone_number_id": "100178282970741",
                        },
                        "contacts": [
                            {
                                "profile": {"name": "OJO TOMISIN ADEDEJI 💊🩺💉🤰🤱"},
                                "wa_id": "2348134732324",
                            }
                        ],
                        "messages": [
                            {
                                "from": "2348134732324",
                                "id": "wamid.HBgNMjM0ODEzNDczMjMyNBUCABIYIDAzRjJGRDUyMTZBMDZFMTA3Qjk1RjE1NzEyMkJERjdGAA==",
                                "timestamp": "1735842923",
                                "type": "reaction",
                                "reaction": {
                                    "message_id": "wamid.HBgNMjM0ODEzNDczMjMyNBUCABEYEjBEMzU2MDdCRjExRTMzNTJGNAA=",
                                    "emoji": "🎉",
                                },
                            }
                        ],
                    },
                    "field": "messages",
                }
            ],
        }
    ],
}
